services:
  flask:
    build:
      context: ./app
    container_name: flask
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - PYTHONPATH=${PYTHONPATH}
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:80"
    command: >
      bash -c "flask run --host=0.0.0.0 --port=80"
