services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped

  apache:
    image: httpd:alpine
    ports:
      - "8081:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/:ro
    restart: unless-stopped
