services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    command: ["nginx", "-g", "daemon off;"]

  apache:
    image: httpd:alpine
    ports:
      - "8081:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/:ro
    restart: unless-stopped
