services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    command: ["nginx", "-g", "daemon off;"]

  flask:
    build:
      context: ./app
    container_name: flask
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - PYTHONPATH=${PYTHONPATH}
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:80"
    command: >
      bash -c "flask run --host=0.0.0.0 --port=80"
